name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    # Runs every 7 days at 00:00 UTC
    - cron: "0 0 */7 * *"
    # For every 15 days, uncomment the below line instead
    # - cron: "0 0 */15 * *"
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true
          tags: |
            kirtiraj027/metta-ci-base:latest
            kirtiraj027/metta-ci-base:${{ github.sha }}
